- README.md
This commit rewraps the README.md content to fit within 80 columns (for
most sane editors :)).  We also add a link pointing visitors to the
mailing list hosted on googlegroups.  Please subscribe!
> Rewrap README.md and add link to mailing list.

- lib/remoteproc/drivers/zynqmp_remoteproc_a53.c
Need to always unmask IPI interrupt since the IPI interrupt
can be initailly masked.
Signed-off-by: Wendy Liang <jliang@xilinx.com>
> remoteproc: zynqmp to a53: always enable IPI intr

- lib/include/openamp/virtio_ring.h
While compilling OpenAMP with a c++ compiler, I encountered an Error originating from the original (void *) cast.
> Fixed cast to (void *) preventing error free compilation with g++

- CMakeLists.txt
- cmake/depends.cmake
- cmake/syscheck.cmake
- lib/CMakeLists.txt
- lib/common/hil.c
- lib/rpmsg/rpmsg_core.c
Enable  to build OpenAMP library for Zephyr
Enable to build OpenAMP library for Zephyr project.
* $ cmake <where_libmetal_is_cloned> -DWITH_ZEPHYR=on \
-DBOARD=qemu_cortex_m3 \
-DCMAKE_INCLUDE_PATH=<built_libmetal_include_path> \
-DCMAKE_LIBRARY_PATH=<built_libmetal_library_path>
* $ make VERBOSE=1 all
> Enable  to build OpenAMP library for Zephyr

- lib/remoteproc/remoteproc.c
original code will hang up in handle_vdev_rsc function.
> fix abort caused by null pointer at rproc->proc.

- lib/include/openamp/rpmsg.h
I replaced rpmsg_alloc_tx_buffer() to with rpmsg_get_tx_payload_buffer().
> fix rpmsg nocopy api comment

- lib/remoteproc/drivers/linux_remoteproc.c
Removes unused and commented out code from the Linux remoteproc driver.
Signed-off-by: Kristian Klomsten Skordal <kristian.skordal@nordicsemi.no>
> remoteproc: remove commented out code

- lib/include/openamp/virtqueue.h
- lib/virtio/virtqueue.c
Some cleanups to the virtqueue implementation to remove some dead code and reduce the struct virtqueue size to drastically reduce the memory requirements for dynamic allocation.
> virtqueue cleanup

- lib/common/hil.c
hil uses sprintf so we need to include stdio.h for it, otherwise we get:
lib/common/hil.c: In function ‘hil_create_generic_mem_dev’:
lib/common/hil.c:112:2: warning: implicit declaration of function ‘sprintf’ [-Wimplicit-function-declaration]
sprintf(dev->name, "%s%lx.%lx", HIL_DEV_NAME_PREFIX, pa,
> hil: fix compile warning

- lib/virtio/virtio.c
Makes lookup tables in the virtio module constant, which allows them to be placed in read-only memory (such as flash) instead of RAM.
These changes cause 72 bytes to be moved to R/O memory.
> Make virtio lookup tables const

- lib/include/openamp/virtqueue.h
Adds an #if around the vq_inuse variable in the virtqueue struct, as
this variable is only used when VQUEUE_DEBUG is set to true.
Signed-off-by: Kristian Klomsten Skordal <kristian.skordal@nordicsemi.no>
> virtqueue: only include vq_inuse in debug mode

- lib/common/sh_mem.c
- lib/include/openamp/sh_mem.h
Change a number of struct elements in sh_mem_pool to unsigned since they
contain values that will (or should) only be unsigned.
> lib: sh_mem: Clean types used in sh_mem_pool

- CMakeLists.txt
If we include open-amp as part of a larger cmake project we should have
project set already so we need to set cmake policy CMP0048.
Also, we should use CMAKE_CURRENT_SOURCE_DIR instead of
CMAKE_SOURCE_DIR.
> cmake: Make it easier to include open-amp in another cmake project

- cmake/options.cmake
Removed WITH_EXT_INCLUDES_FIND as there is nothing that references or
uses it.
> cmake: Remove dead cmake option

- apps/examples/echo/rpmsg-echo.c
- apps/examples/echo/rpmsg-ping.c
- apps/examples/matrix_multiply/matrix_multiply.c
- apps/examples/matrix_multiply/matrix_multiplyd.c
- apps/examples/rpmsg_sample_echo/rpmsg-sample-echo.c
- apps/examples/rpmsg_sample_echo/rpmsg-sample-ping.c
Previously, init_system and cleanup_system were used within the
applications. Remove as they are no longer called in the application
files.
> apps: remove unused functions

- lib/remoteproc/elf_loader.c
When there's no more segment to load, return success so that the caller
can proceed with further operations.
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
> remoteproc: elf_loader: Return success on no more loadable segment

- lib/include/openamp/virtio_ring.h
A comment block in virtio_ring.h describes vring layout, and according
to this commnt, __u16 used_event_idx is a member of struct vring.
virtio_ring.h provided by Linux Kernel properly takes this member
into account in vring_size() and vring_init(). Whereas virtio_ring.h
in OpenAMP, vring_size() is aware of used_event_idx but vring_init()
forgets to add __u16 storage to calculate the offset of used member.
Typically aling passed to vring_size() and vring_init() is 0x1000,
so this is not a problem, but fix this for consistency.
Signed-off-by: Hiroaki SHIMODA <hiroaki.shimoda@miraclelinux.com>
> virtio: Fix offset of struct vring::used

- lib/include/openamp/remoteproc_virtio.h
- lib/remoteproc/remoteproc_virtio.c
On slave side, during the init sequence we need to wait
the vdev status before calling rproc_virtio_init_vring.
Indeed the virtual address(VA), provided as function
parameter, is based on the device address(DA).
Depending on the environment this DA is retrieved from
the resource table, filled by the master processor.
this service allow to block the processor waiting the
status update.
> remoteproc: virtio: add service to get vdev status.

- lib/include/openamp/remoteproc.h
- lib/include/openamp/rpmsg.h
- lib/proxy/rpmsg_retarget.c
- lib/remoteproc/elf_loader.c
- lib/remoteproc/remoteproc.c
- lib/remoteproc/remoteproc_virtio.c
The remoteproc implementation uses both error code from c library and remoteproc definition.
We should just use remoteproc defined error code for consistency.
For the rpmsg_retarget.c, it redefine c library file operations, it uses c library error code, it should include error.h header.
> Fix errors

- lib/rpmsg/rpmsg_virtio.c
If the length in buffer descriptor is 0 or less then the
RPMsg header, return 0.
Signed-off-by: Wendy Liang <wendy.liang@xilinx.com>
> rpmsg: virtio: fix get buffer size return

- lib/include/openamp/rpmsg.h
- lib/rpmsg/rpmsg_virtio.c
since the successful return value from many function is greater than zero
> assert only when status < 0 in rpmsg_virtio_rx_callback

- apps/machine/zynqmp/openamp-linux-userspace.dtsi
Update to match default shared memory configuration.
> apps: zynqmp userspace: update dts shared mem node

- lib/include/openamp/virtqueue.h
Nested structs and unions have different visibility rules in C and C++.
Fixes #178
> Remove nested structs in header

- MAINTAINERS.md
Add Arnaud and Ed as project maintainers
Add Ed as Xilinx platform maintainer
> Maintainers: update project maintainers

- lib/include/openamp/elf_loader.h
- lib/include/openamp/remoteproc.h
- lib/include/openamp/remoteproc_loader.h
- lib/proxy/rpmsg_retarget.c
- lib/remoteproc/elf_loader.c
- lib/remoteproc/remoteproc.c
- lib/remoteproc/rsc_table_parser.c
- lib/rpmsg/rpmsg_virtio.c
- lib/virtio/virtqueue.c
This series proposes corrections for few compilation issues and issues reported by IAR c-stat tools  (alignment with MISRA C 2012)
Only one c-stat report as not been fixed, as seems related to a false positive:
rsc_table_parser.c	52	Array pointer `rsc_table' is accessed with index [8,8] which may be out of array bounds [0,UNKNOWN]
rsc_table_parser.c	52	array pointer `rsc_table' is accessed with index [9,9] which may be out of array bounds [0,UNKNOWN] 
This seems not possible as 'reserved' 2 word array is defined in the resource table header.
> compilation warnings and IAR c-stat reports

- MAINTAINERS.md
> Maintainers: update ED Mooring mail address

- lib/rpmsg/rpmsg_virtio.c
This PR fixes the "run flood" test fails ovbserved on x86 machine
- Issue:
"rpmsg_send failed" message 
- to reproduce the issue:
1) compile libmetal
rm -r build
cmake . -Bbuild 
cd build
make
2) compile OpenAMP lib
cmake . -DWITH_APPS=on -DWITH_PROXY=on -Bbuild -DCMAKE_INCLUDE_PATH="../libmetal/build/lib/include" -DCMAKE_LIBRARY_PATH="../libmetal/build/lib"
cd build
make install DESTDIR=./bin
3) run test
LD_LIBRARY_PATH=./bin/usr/local/lib:../../libmetal/build/lib/  ./bin/usr/local/bin/rpmsg-echo-shared &
sleep 1
LD_LIBRARY_PATH=./bin/usr/local/lib:../../libmetal/build/lib/  ./bin/usr/local/bin/msg-test-rpmsg-flood-ping-shared 1
> rpmsg: don't return error when no more buffer available but wait

- apps/system/linux/machine/generic/platform_info.c
This change caused a compilation failure when compiling the OpenAMP examples on Linux due to a missing include file and some experimental changes to the libmetal shared memory API.
Signed-off-by: Ed Mooring <ed.mooring@linaro.org>
> examples: Remove stray local change from Linux platform_info.c

- lib/include/openamp/virtio_ring.h
This is done in order to avoid a compiler warning from
the -Wcast-align flag.
> Pack the vring_desc and vring_avail structs

- lib/CMakeLists.txt
All that the zephyr_library_named(foo) function guarantees is that
after calling it, the variable ${ZEPHYR_CURRENT_LIBRARY} evaluates to
the target name for the library named foo. In particular, it does not
guarantee that the name of the target is also foo, which the open-amp
build system currently assumes.
(It happens to be true right now, but it's an abstraction violation.)
Fix things by using the ZEPHYR_CURRENT_LIBRARY and one of its helpers.
Signed-off-by: Marti Bolivar <marti.bolivar@nordicsemi.no>
> cmake: fix zephyr library abstraction violation

- .github/workflows/continuous-integration.yml
Create a first checkpatch test for continuous integration
this job runs the checkpatch action from
https://github.com/webispy/checkpatch-action
> Create CI checkpatch test using github workflow

- cmake/options.cmake
Add option to adjust RPMSG_BUFFER_SIZE during CMake build
> Adjustable rpmsg size

- .gitlint
- scripts/gitlint/commit_rules.py
Add gitlint configuration to allow contributor to check its
commit message compliance before sending its pull request.
The configuration files has been copied from Zephyr project.
> gitlint: add giltlint configuration files

- apps/examples/echo/rpmsg-echo.c
- apps/examples/echo/rpmsg-ping.c
- apps/examples/matrix_multiply/matrix_multiply.c
- apps/examples/matrix_multiply/matrix_multiplyd.c
- apps/examples/rpc_demo/rpc_demod.c
- apps/examples/rpmsg_sample_echo/rpmsg-sample-echo.c
- apps/examples/rpmsg_sample_echo/rpmsg-sample-ping.c
- apps/tests/msg/rpmsg-flood-ping.c
- apps/tests/msg/rpmsg-ping.c
- apps/tests/msg/rpmsg-update.c
the example should demo the best practice for the endpoint creation
> apps: replace all zero address to RPMSG_ADDR_ANY

- lib/rpmsg/rpmsg.c
since the NS message shouldn't use for all well known services
> rpmsg: send RPMSG_NS_DESTROY only when addr >= 1024

- CMakeLists.txt
emoves the following warning when using newer CMake versions:
```
Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
--help-policy CMP0077" for policy details.  Use the cmake_policy command
to set the policy and suppress this warning.`
```
Both OLD and NEW behavior will use the value defined earlier in the
CMake process, however the OLD behavior will also add an entry to the
CMakeCache.txt but ignore that value on sub-sequent invocations.
As this may lead to confusion on users looking into the CMakeCache.txt,
then the best is to not get such values into the cache, and thus use NEW
behavior.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>
> cmake: set the policy CMP0077 to NEW

- lib/include/openamp/virtqueue.h
Merging this ensures that all open-amp headers can be included in a C++ translation unit without the compiler throwing errors.
This was tested with GCC 7.3.1 for arm64 with `std=c++17`.
> Ensure C++ compatibility of headers

- apps/machine/zynqmp/platform_info.c
- apps/machine/zynqmp/platform_info.h
- apps/machine/zynqmp/zynqmp_linux_r5_proc.c
- apps/machine/zynqmp_r5/platform_info.c
- apps/machine/zynqmp_r5/platform_info.h
- apps/machine/zynqmp_r5/zynqmp_r5_a53_rproc.c
There are use cases where IPI is not available so add switch in Xilinx R5 demos to run without the use of IPI and instead only poll via shared memory.
> Xilinx A53 to R5 Demos without ipi

- lib/include/openamp/rpmsg.h
- lib/rpmsg/rpmsg.c
- lib/rpmsg/rpmsg_internal.h
- lib/rpmsg/rpmsg_virtio.c
This PR is related to the issue OpenAMP/open-amp#220
The rpmsg_init_ept does not seem to be usable by application
but is used internally. This patch mark this API deprecated
and in at least two full release, to remove this API as the
standard API to use is rpmsg_create_ept.
In addition, move the rpmsg_init_ept to rpmsg_internal.h and rename it.
> rpmsg: set rpmsg_init_ept API as deprecated

- apps/examples/load_fw/common.h
- apps/examples/load_fw/mem_image_store.c
- apps/examples/rpc_demo/rpc_demod.c
- apps/machine/zynq7/platform_info.c
- apps/machine/zynqmp/platform_info.c
- apps/machine/zynqmp_r5/platform_info.c
- apps/system/linux/machine/generic/platform_info.c
When building OpenAMP apps for FreeRTOS on Xilinx hardware, there
were compile errors due to EINVAL not being defined. On other
platforms, <errno.h> was implicitly included by OpenAMP header
files. This change explicitly includes it where it is needed
in the code.
> Add <errno.h> explicitly to all files that use errno values.

- .github/actions/build_ci/Dockerfile
- .github/actions/build_ci/README.md
- .github/actions/build_ci/action.yml
- .github/actions/build_ci/entrypoint.sh
- .github/workflows/compliance.yml
- .github/workflows/continuous-integration.yml
Add build tests for Linux, arm platform and zephyr.
No build test for freeRTOS as the openamp library is relying on libmetal and so is FreeRTOS agnostic  
Notice that for Zephyr,the openamp and libmetal repos have been forked.
As consequence for the build the associated openamp and libmetal modules are updated with the current version including new patches and some Zephyr samples are compiled idirectly in the zephyr  environment.
> CI tests: add build test actions

- apps/machine/zynqmp/zynqmp_linux_r5_proc.c
no-ipi patches seemed to have caused compilation issue. resolve here
> apps: zynqmp: fix compilation issue from rebase

- apps/examples/echo/rpmsg-ping.c
- apps/machine/zynq7/platform_info.c
- apps/machine/zynqmp/platform_info.c
- apps/machine/zynqmp_r5/platform_info.c
- apps/system/linux/machine/generic/platform_info.c
- apps/tests/msg/rpmsg-flood-ping.c
- apps/tests/msg/rpmsg-ping.c
For each metal_allocate_memory call, make sure there are
subsequent metal_free_memory calls
for https://github.com/OpenAMP/open-amp/issues/230
> apps: update memory management

- lib/include/openamp/rpmsg.h
- lib/rpmsg/rpmsg.c
- lib/rpmsg/rpmsg_virtio.c
Align with other rpmsg_send_xxx function naming convention, no functionality change.
> rename size parameter to len for rpmsg_send_offchannel_raw

- lib/rpmsg/rpmsg_virtio.c
rpmsg_virtio_get_tx_buffer shouldn't allocate the number of
buffer bigger than the virtio ring length of sending
report here: https://github.com/OpenAMP/open-amp/pull/162#discussion_r513496611
> rpmsg: virito: limit the buffer allocate from shared memory pool

- apps/examples/rpc_demo/rpc_demod.c
The GCC compiler complains about the printf of a size_t variable.
add 'z' length modifier to fix the warning.
> apps: rpc_demo: fix compilation warning

- lib/rpmsg/rpmsg_virtio.c
openamp: rpmsg_send() shouldn't check buffer size when get buffer failed
cause _rpmsg_virtio_get_buffer_size() always return size > 0,
when role is RPMSG_MASTER.
openamp: fix ns_unbind_cb error when meet RPMSG_NS_DESTROY
> Openamp bug fix on RPMSG_NS_DESTROY & rpmsg_send failed

- lib/include/openamp/remoteproc.h
- lib/remoteproc/remoteproc.c
1.change va from output to input/output
2.remoteproc_get_io_xxx fallback to mmap callback
> remoteproc: add get_mem callback to remoteproc_ops

- apps/machine/microblaze_generic/platform_info.c
Fix duplicated function definition with bad code.
See https://github.com/OpenAMP/open-amp/issues/252
Signed-off-by: Sergei Korneichuk <sergei.korneichuk@xilinx.com>
> apps: machine: Fix MicroBlaze compilation error

- lib/include/openamp/virtqueue.h
Fix compilation error when defining macro ”VQUEUE_DEBUG“.
> Fix compilation error.Add missing semicolon.

- .github/workflows/compliance.yml
A false positive is returned by the compliance check when the script crashes.
This pull request is a cherry-pick of the Zephyr project that already fixes the issue
- fix the script to return fail, in case of crash,
- fix the crash linked to junitparser library version compatibility.
> CI Fix compliance  test

- lib/rpmsg/rpmsg_virtio.c
The idx variable size is 16-bit. Add a cast to fix "expression may overflow"
code analysis complain.
> rpmsg: fix variable overflow

- .github/actions/build_ci/entrypoint.sh
When only the libmetal/lib is copied, some files such as VERSION or CmakeList.txt are not copied. This can lead to a test error or false positives.
This PR  fixes CI test that does not highlight issue resolved in the https://github.com/OpenAMP/libmetal/pull/154.
> CI: Zephyr test: copy whole libmetal directory for test

- .github/actions/build_ci/entrypoint.sh
Update zephyr SDK to 0.12.4 to fix CI compatibility issue.
A similar PR has already been reviewed and applied in the libmetal repo: https://github.com/OpenAMP/libmetal/pull/161
> CI: Fix Zephyr build by updating Zephyr SDK version

- README.md
- cmake/options.cmake
- lib/rpmsg/rpmsg_virtio.c
- lib/virtio/virtqueue.c
On some platforms the VirtQueue and Vring structures could be stored in cacheable memory. When a data cache is present OpenAPM should take care of flushing / invalidating vring structures and control block when needed to keep consistency, this should be done using the metal_cache_* APIs.
This is an RFC and I'm open to any comment / suggestion on how to address this issue the proper way.
Fixes: #292
Signed-off-by: Carlo Caione <ccaione@baylibre.com>
> virtqueue:  Introduce cache helpers

- .github/actions/build_ci/entrypoint.sh
Update zephyr SDK to 0.13 to fix CI compatibility issue.
The name of the steup file has also be updated.
> CI: Fix Zephyr build by updating Zephyr SDK version to 13.0

- .github/actions/build_ci/entrypoint.sh
CMake 3.20.0 or higher is required by Zephyr.
Use pip3 as recommended by zephyr project to get the last version.
> CI: Fix Zephyr build by cmake version

- .github/workflows/compliance.yml
- .github/workflows/continuous-integration.yml
Rename branch for CI and compliance checks to "main".
Signed-off-by: Ed Mooring <ed.mooring@gmail.com>
> CI: Update branch from "master" to "main".

- lib/remoteproc/rsc_table_parser.c
Fix the issue that it used vring_rsc->notifyid to allocate new IDs but
finally updated vdev_rsc->notifyid rather than vring_rsc->notifyid.
(See https://github.com/OpenAMP/open-amp/issues/314)
Signed-off-by: Junyan Lin <junyanlin@allwinnertech.com>
> remoteproc: fix notifyid assignment in handle_vdev_rsc

- lib/include/openamp/rpmsg_virtio.h
- lib/rpmsg/rpmsg_virtio.c
Fixes #322 
Enable user of rpmsg_virtio to set sizes of TX and RX buffers per
created rpmsg_virtio instance. Each instance can use other buffer sizes.
Signed-off-by: Hubert Miś <hubert.mis@nordicsemi.no>
> rpmsg_virtio: configuration option to set buffer sizes per instance

- lib/include/openamp/rpmsg_virtio.h
- lib/rpmsg/rpmsg_virtio.c
and define it to NULL when VIRTIO_SLAVE_ONLY is defined to save space
> rpmsg_virtio: move RPMSG_VIRTIO_DEFAULT_CONFIG to private location

- lib/rpmsg/rpmsg.c
- lib/rpmsg/rpmsg_internal.h
- lib/rpmsg/rpmsg_virtio.c
so the service with preserved address could call rpmsg_register_endpoint only
> rpmsg: merge rpmsg_initialize_ept into rpmsg_register_endpoint

- lib/remoteproc/remoteproc.c
- lib/virtio/virtqueue.c
1. fix remoteproc get wrong memory when memory region are continuous.
2. fix Invalidate the ring region but use non initialize ring index.
Signed-off-by: Joshua Lin <jlin@petaio.com>
> fix remoteproc get wrong memory when memory region are continuous and Invalidate the ring region but use non initialize ring index.

- lib/remoteproc/remoteproc.c
remoteproc: fix memory issue if load resource table failed
> remoteproc: fix memory issue if load resource table failed 

- lib/rpmsg/rpmsg.c
Case for src and dest address is unused since the first case matches src only.
> Removed unused code from rpmsg_get_endpoint

- .github/workflows/compliance.yml
- scripts/checkpatch.pl
- scripts/ci/check_compliance.py
The checkpatch.pl allows to run codespell on patches to highlight typo error.
Rebase the CI and checkpatch script on recent version and enable "codespell" tool
> CI: enable codespell check

- apps/machine/zynqmp/platform_info.c
- apps/machine/zynqmp/platform_info.h
- apps/machine/zynqmp_r5/platform_info.c
- apps/machine/zynqmp_r5/platform_info.h
- apps/machine/zynqmp_r5/rsc_table.c
- apps/system/generic/machine/zynqmp_r5/CMakeLists.txt
- apps/system/generic/machine/zynqmp_r5/helper.c
- apps/system/generic/machine/zynqmp_r5/linker_large_text.ld
- apps/system/generic/machine/zynqmp_r5/linker_remote.ld
Currently the demos' interrupt, shared memory and IPC structure values are hard-coded.
Allow these to configured via CMake configure by 
(a) wrapping C symbols in #ifdef / #ifndef
(b) enabling linker script defined resource table location to be set in CMake.
> Enable OpenAMP Demo configuration via CMake

- lib/virtio/virtqueue.c
Ensure there is enough room for all the buffers being added to the vring.
Signed-off-by: Tammy Leino tammy_leino@mentor.com
> virtqueue_add_buffer must check that there is room for multiple buffers

- lib/remoteproc/remoteproc.c
remoteproc_virtio_notify updated to check notify operation before invoking.
> remoteproc_virtio_notify could use null notify operation

- lib/include/openamp/remoteproc.h
Added a description of the buf parameter to get_mem.
> Document buf argument in get_mem for remoteproc_ops structure

- lib/remoteproc/remoteproc.c
Modified remoteproc_get_mem to bound the name comparison by RPROC_MAX_NAME_LEN instead of the length of the incoming search string
> remoteproc_get_mem could wrongly match on wrong name

- lib/rpmsg/rpmsg_virtio.c
The code wrongly returns 0 if a descriptor is not available.
> _rpmsg_virtio_get_buffer_size should return error on failure

- README.md
- apps/examples/echo/rpmsg-echo.c
- apps/examples/echo/rpmsg-ping.c
- apps/examples/linux_rpc_demo/linux_rpc_demo.c
- apps/examples/linux_rpc_demo/linux_rpc_demod.c
- apps/examples/matrix_multiply/matrix_multiply.c
- apps/examples/matrix_multiply/matrix_multiplyd.c
- apps/examples/nocopy_echo/rpmsg-nocopy-echo.c
- apps/examples/nocopy_echo/rpmsg-nocopy-ping.c
- apps/examples/rpc_demo/rpc_demo.c
- apps/examples/rpc_demo/rpc_demod.c
- apps/examples/rpmsg_sample_echo/rpmsg-sample-echo.c
- apps/examples/rpmsg_sample_echo/rpmsg-sample-ping.c
- apps/machine/zynq7/platform_info.c
- apps/system/linux/machine/generic/platform_info.c
- apps/tests/msg/rpmsg-flood-ping.c
- apps/tests/msg/rpmsg-ping.c
- apps/tests/msg/rpmsg-update.c
- cmake/options.cmake
- lib/include/openamp/rpmsg_virtio.h
- lib/include/openamp/virtio.h
- lib/remoteproc/remoteproc_virtio.c
- lib/rpmsg/rpmsg_virtio.c
- lib/virtio/virtio.c
- lib/virtio/virtqueue.c
The OpenAMP project Technical Steering Committee has requested that potentially objectionable terms be removed from the OpenAMP code base. This is the first step in removing them. It replaces these terms in variable/identifier names within the code base. 
Further pull requests will fix the documentation and comments in the code.
> Replace potentially objectionable terms in OpenAMP variable names.

- apps/system/generic/machine/zynqmp_r5/CMakeLists.txt
While building the Xilinx R5 demo apps, the following error message
occurs:
CMake Error at apps/examples/echo/CMakeLists.txt:38 (add_executable):
Target "rpmsg-echo.out" links to item " -Wl,--defsym,_rsc_table=0x3ed20000
-T"/OpenAMP-Project/gh3/open-amp/apps/system/generic/machine/zynqmp_r5/linker_remote.ld""
which has leading or trailing whitespace.  This is now an error according
to policy CMP0004.
Remove the leading space.
Signed-off-by: Ed Mooring <ed.mooring@gmail.com>
> apps: Remove leading space in CMake linker directive variables.

- docs/rpmsg-design.md
- lib/include/openamp/rpmsg.h
- lib/rpmsg/rpmsg_virtio.c
it's useful to notify the port layer and also symmetry with ns_bind_cb callback.
> openamp: add ns_unbind_cb to rpmsg_device

- cmake/platforms/cross_generic_gcc.cmake
Building OpenAMP for standalone ARM R5, the following warning occurs:
CMake Deprecation Warning at
/usr/share/cmake-3.16/Modules/CMakeForceCompiler.cmake:75 (message):
The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
cmake/platforms/cross_generic_gcc.cmake:5 (CMAKE_FORCE_C_COMPILER)
/home/mooring/build-oa/toolchain.r5-oa.sa:18 (include)
/usr/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:93 (include)
CMakeLists.txt:19 (project)
Follow the suggestions in the above error message, and add
CMAKE_TRY_COMPILE_TARGET_TYPE = STATIC LIBRARY, which makes try_compile()
not try to link the cross-compiled binary. This is necessary because the
arm-none-eabi toolchain libgcc doesn't have …
> Fix CMake Deprecation Warnings

- lib/proxy/rpmsg_retarget.c
- lib/remoteproc/rsc_table_parser.c
There were several places in the library where a char* was used to point
to a wider type (uint32_t or a struct). Casting the char* to the wider
type resulted in a compiler warning.
This commit adds a cast to void* to remove the compiler warnings. This
results in no functional change.
Signed-off-by: Ed Mooring <ed.mooring@gmail.com>
> lib: Remove warnings from -Wcast-align

- lib/remoteproc/remoteproc_virtio.c
Added macros to omit code when compiling for device-only.
> Add missing macros for driver/device-only compilation

- lib/virtio/virtqueue.c
head_idx must be restricted to 0 ... vq_nentries - 1
> virtqueue_add_consumed_buffer input parameter fix

- .github/actions/build_ci/entrypoint.sh
Update zephyr SDK to 0.15.0 to fix CI build issue.
> CI: Fix Zephyr build by updating Zephyr SDK version to 0.15.0

- lib/include/openamp/remoteproc.h
- lib/include/openamp/rpmsg.h
- lib/include/openamp/rpmsg_virtio.h
- lib/remoteproc/remoteproc.c
- lib/remoteproc/remoteproc_virtio.c
- lib/remoteproc/rsc_table_parser.c
- lib/rpmsg/rpmsg.c
- lib/rpmsg/rpmsg_virtio.c
Added additional input parameter checks to APIs
> Additional input parameter checks for APIs

- apps/examples/linux_rpc_demo/linux_rpc_demo.c
No symbols from rsc_table.h are used in linux_rpc_demo.c and the demo fails to build. Remove include rsc_table.h.
Signed-off-by: Sergei Korneichuk <sergei.korneichuk@amd.com>
> linux_rpc_demo: do not include rsc_table.h

- lib/include/openamp/remoteproc_virtio.h
- lib/remoteproc/remoteproc_virtio.c
Code must ensure we don't overflow the 16-bit count in vring_alloc_info
> Vring descriptor count must be limited to 65k per device

- lib/include/openamp/remoteproc.h
- lib/remoteproc/remoteproc.c
- lib/remoteproc/rsc_table_parser.c
notifyid is 32 bits in the resource table and must be uint32_t in code
> remoteproc_allocate_id not treating notifyid as 32-bits

- lib/include/openamp/rpmsg_virtio.h
- lib/rpmsg/rpmsg_virtio.c
openamp: divide shram to TX shram & RX shram 
Signed-off-by: Guiding Li <liguiding1@xiaomi.com>
Signed-off-by: Jiuzhu Dong <dongjiuzhu1@xiaomi.com>
> openamp: divide shram to TX shram & RX shram

- lib/rpmsg/rpmsg_virtio.c
openamp: should kick remote when use release_rx_buffer
There is missing virtqueue_kick when use hold_rx/release_rx
Signed-off-by: Guiding Li <liguiding1@xiaomi.com>
> openamp: should kick remote when use release_rx_buffer

- README.md
The instructions to build open-amp for zephyr do not work. Instead of trying to maintain a cross dependency between the zephyr and the open-amp, just reference the zephyr project and documentation
> README: Remove deprecated method to build open-amp lib for zephyr

- apps/examples/rpc_demo/rpc_demo.c
rpc_demo.c file creates firmware that runs on remote processor. The current description implies that proxy service is implemented on remote side which is not true. Fix description and explicitly mention that proxy service is implemented on host side.
> Update rpc_demo description

- lib/remoteproc/remoteproc_virtio.c
The arm-none-eabi-gcc complains when VIRTIO_DEVICE_ONLY is enable
remoteproc_virtio.c:222:29: warning: variable 'vring_rsc' set but not used [-Wunused-but-set-variable]
222 |   struct fw_rsc_vdev_vring *vring_rsc;
|                             ^~~~~~~~~
The vring_rsc variable should be declared and set only if VIRTIO_DEVICE_ONLY is not enable.
> remoteproc: Fix build warning in rproc_virtio_create_vdev function

- apps/machine/zynqmp_r5/rsc_table.c
The notifyid for the virtio device in the resource table was set to 0, and the notifyids for the vrings were set to 1 and 2. However, the Linux remoteproc implementation changes those values to 0 and 1 when the firmware image is loaded. With the enhanced error checking introduced in commit 2016ff1e, the duplicate assignment of notifyid 0 to the rvdev and vring0 resulted in a failure.
Set the value of notifyid for the virtio device (rvdev) to 31 to avoid possible conflicts with the Linux imposed values.
> zynqmp_r5 resource table: Change notifyid for the virtio device.

- lib/remoteproc/rsc_table_parser.c
```
regressed by commit 03c80a13417f67f94852cf7d5cb160f1bdf8271e
Author: Tammy Leino <tammy_leino@mentor.com>
Date:   Mon Sep 26 08:14:35 2022 -0700
handle_vdev_rsc must return error if notifyid cannot be assigned
Updated handle_vdev_rsc to return error if a unique id cannot be assigned
```
> Fix warn: declaration of 'vring_rsc' shadows a previous local

- .github/actions/build_ci/entrypoint.sh
- apps/examples/linux_rpc_demo/linux_rpc_demo.c
- apps/examples/linux_rpc_demo/linux_rpc_demod.c
- apps/examples/nocopy_echo/rpmsg-nocopy-ping.c
- apps/tests/msg/rpmsg-nocopy-ping.c
Based on https://github.com/OpenAMP/open-amp/pull/439
- Fix shadows warning in applications.
- Add new build flags to highlight warnings and treat warnings as an errors
> Fix shadow warnings in application code and renforce CI build

- cmake/options.cmake
- lib/include/openamp/virtio_mmio.h
- lib/include/openamp/virtio_mmio_hvl.h
- lib/virtio/virtqueue.c
- lib/virtio_mmio/CMakeLists.txt
- lib/virtio_mmio/virtio_mmio.c
- lib/virtio_mmio/virtio_mmio_hvl.c
OpenAMP library support for VIRTIO MMIO network, entropy and console in hypervisorless VIRTIO operation mode.
Validated using Zephyr environment based on https://github.com/OpenAMP/openamp-zephyr-staging/tree/virtio-exp.
Build tools for complete hypervisorless virtio system (Xilinx ZCU 102) are available here: https://github.com/danmilea/hypervisorless_virtio_zcu102/
Additional hypervisorless virtio information:
https://github.com/danmilea/hypervisorless_virtio_zcu102/blob/main/README_hypervisorless_virtio.md
> virtio-mmio: hypervisorless mode

- README.md
Fix broken link that gives "page not found".
Signed-off-by: Hiago De Franco <hiagofranco@gmail.com>
> readme: Fix broken openamp-rp mailing list link

- lib/remoteproc/remoteproc.c
Signed-off-by: Ben Levinsky <ben.levinsky@amd.com>
> openamp: fix remoteproc_load_noblock hasn't update rsc_io

- lib/rpmsg/rpmsg_virtio.c
rpmsg: do cache_invalidate() when real data returned
> BUGFIX: rpmsg: do cache_invalidate() when real data returned

- apps/examples/linux_rpc_demo/linux_rpc_demo.c
- apps/system/linux/machine/generic/platform_info.c
- lib/include/openamp/rpmsg_retarget.h
- lib/proxy/rpmsg_retarget.c
This patch tries to fix issue#471
> BUGFIX: change unsuitable atomic_int to atomic_flag

- apps/machine/microblaze_generic/rsc_table.c
- apps/machine/zynq7/rsc_table.c
The open-amp apps are failing on zynq7 with "Failed to initialize remoteproc" after v2022.10.0 update.
Port commit 46d041808804 ("zynqmp_r5 resource table: Change notifyid for the virtio device.") to zynq7 and microblaze.
> zynq7, microblaze resource table: virtio notifyid

- lib/rpmsg/rpmsg_virtio.c
rpmsg: add cache flush when hold rx buffer
Here is the bug:
Assume we have 2 cpus, and use cached shram buffer
```
CPU0                        CPU1
1. send tx bufferX  
2. recv rx bufferX  
3. set idx to hdr->reserved 
4. handled rx bufferX 
5. return bufferX
6. reuse tx bufferX 
7. dirty cache auto flushed cause by step 3, hdr changed by CPU1
8. bufferX meet error
```
So, can we use the cache flush to resolve the issue or other ways ?
> BUG FIX: rpmsg: add cache flush when hold rx buffer

- scripts/checkpatch.pl
Fix issue https://github.com/OpenAMP/open-amp/issues/483
A false positive is "doesn't".  Occurrence of the word causes checkpatch
to emit the following warning:
"WARNING: 'doesn'' may be misspelled - perhaps 'doesn't'?"
The PR is a cherry pick of from Linux kernel:
https://lore.kernel.org/all/20201201190729.169733-1-dwaipayanray1@gmail.com/T/#u
> checkpatch: fix TYPO_SPELLING check for words with apostrophe

- Doxyfile
- lib/include/openamp/elf_loader.h
- lib/include/openamp/remoteproc.h
- lib/include/openamp/remoteproc_virtio.h
- lib/include/openamp/rpmsg.h
- lib/include/openamp/rpmsg_retarget.h
- lib/include/openamp/rpmsg_rpc_client_server.h
- lib/include/openamp/rpmsg_virtio.h
- lib/include/openamp/rsc_table_parser.h
- lib/include/openamp/version.h
- lib/include/openamp/virtqueue.h
- lib/remoteproc/rsc_table_parser.c
- lib/rpmsg/rpmsg.c
- lib/rpmsg/rpmsg_virtio.c
- lib/virtio/virtqueue.c
Updated function header descriptions formatting to be consistent.
Signed-off-by: Tammy Leino <tammy.leino@siemens.com>
> Function header description consistency

- apps/machine/zynqmp/platform_info.c
Enable Linux demos to run on Versal_net by updating the IPI values that are specific to this hardware platform.
> apps: zynqmp: Add Versal_net IPI values.

- .github/workflows/continuous-integration.yml
Node.js 12 actions are deprecated. Use the checkout V3 action to use Node.js 16
> CI: update checkout action to V3

- lib/include/openamp/virtio.h
- lib/virtio/virtio.c
Follow virtio v1.2 spec, add more virtio status and device id. I change the device id from hexadecimal to decimal, because the virtio v1.2 spec use decimal.
Make commit 1 in https://github.com/OpenAMP/open-amp/pull/489 be an independent PR.
Should be none.
> virtio: follow virtio 1.2 spec, add more virtio status and device id

- .github/workflows/compliance.yml
- scripts/ci/check_compliance.py
The CI does not consider "check" reported by checkpatch. This commit fixes it by:
- rebasing check_compliance.py compliance.yml to integrate Zephyr updates,
- add detection of the "check" in the report.
An exemple of the result is available here: https://github.com/arnopo/open-amp/pull/25
> CI: Fix checkpatch

- lib/include/openamp/virtio.h
- lib/virtio/virtio.c
This is the first step to decoupling the virtio deivce and transport layer.
Related issue: https://github.com/OpenAMP/open-amp/issues/390#issuecomment-1602605560
@arnopo Could take a look?
> virtio: add create_virtqueues and delete_virtqueues in virtio_dispatch

- README.md
- cmake/options.cmake
- lib/include/openamp/remoteproc_virtio.h
- lib/include/openamp/rpmsg_virtio.h
- lib/include/openamp/virtqueue.h
- lib/rpmsg/rpmsg_virtio.c
- lib/virtio/virtqueue.c
Please, check each commit.
cc: @arnopo @carlocaione @TanmayShah-xilinx
> Updates and clean-up cache management

- Doxyfile
- lib/include/openamp/remoteproc.h
- lib/include/openamp/remoteproc_loader.h
- lib/include/openamp/remoteproc_virtio.h
- lib/include/openamp/rpmsg.h
- lib/include/openamp/rpmsg_rpc_client_server.h
- lib/include/openamp/rpmsg_virtio.h
- lib/include/openamp/virtio.h
- lib/include/openamp/virtio_mmio.h
- lib/include/openamp/virtio_ring.h
- lib/rpmsg/rpmsg_internal.h
Improved doxygen formatting and consistency for data structures.
Signed-off-by: Tammy Leino <tammy.leino@siemens.com>
> Doxygen updates for data structures

- .readthedocs.yaml
The Readthedocs pull-request integration is nice to have for PR review. So run the whole OpenAMP-docs build but use the PR's commit
This also requires a ReadTheDocs project to install its integration for this repo. The project should enable "Build pull request for this project". It is currently in the Advanced Settings panel.
The project will also run for the main branch but that should be ignored and only the main project URL should be shown outside of PRs.
To this end the sub-module project names will use "-prs" in the name.
> Docs: enable readthedocs rendering (for PRs)

- doc/CMakeLists.txt
Detect when we are a submodule of OpenAMP-docs.
If so use the top level's Doxyfile overrides on top of our Doxyfile. If not, no change.
> Docs: style doxygen when built as part of OpenAMP docs

- lib/include/openamp/virtio.h
- lib/virtio/virtio.c
The virtio_describe() function does not seem usable. Therefore, it should be marked as deprecated to initiate the removal process.
> virtio: make unused function virtio_describe() deprecated

- lib/include/openamp/virtio.h
The function should return void. the reason is that vdev->func->delete_virtqueues() is optional and return void.
To be generic we should call virtio_delete_virtqueues in all cases. Then depending on the dispatcher we do nothing or call delete_virtqueues()
Fixes: 7f90610 ("virtio: add create_virtqueues and delete_virtqueues in virtio_dispatch")
> virtio: Fix delete_virtqueues function

- .github/workflows/stales.yml
By default the action closes the PR or issue 7 days after adding the stale label.
The expected behavior is that the pull requests and issues will never be closed automatically by the bot.
> github action: Fix stales action to not close PR/issue after 7 days

- README.md
Update documentation reference and wrap long lines.
> Readme improvement for v2023.10 release

- lib/include/openamp/rpmsg.h
- lib/rpmsg/rpmsg.c
rpmsg: set ept address to incease num when alloc from the bitmap
CPU0                                CPU1
create_ept1:addr1                   create_ept1
OK                       <======    msg1
OK                       <======    msg2
OK                       <======    msg3
msg4
<======    msg4 on the virtioqueue
close_ept1                          close_ept1
create_ept2:addr1                   create_ept1
(same addr with ept1)
msg4
ept2 recv ept1 msg ERROR <======
The msg4 which belong to ep1, error received by ept2.
For the issue, I give a resolve method,
for the rpmsg_get_address(), always return a new increased num.
This should compile with https://github.com/OpenAMP/libmetal/pull/263
> rpmsg: set ept address to incease num when alloc from the bitmap

- lib/include/openamp/rpmsg_virtio.h
- lib/rpmsg/rpmsg_virtio.c
With this API, user can get the rx buffer size, and use this buffer safer in endpoint callback function.
Follow shows an example:
```c
static int rpmsgfs_ept_cb(FAR struct rpmsg_endpoint *ept,
FAR void *data, size_t len, uint32_t src,
FAR void *priv)
{
/* No need extra stack variable or malloced buffer, user can fill the response data in the data directly,
* And to avoid the data overflow, user can call rpmsg_virtio_get_rx_buffer_size() to get the limitation
* of input data.
*/
/* Call rpmsg_send(ept, data, data_len) to send the response data */
rpmsg_send(ept, data, len);
}
```
> openamp: add new API rpmsg_virtio_get_rx_buffer_size()

- apps/examples/echo/rpmsg-echo.c
- apps/examples/echo/rpmsg-ping.c
- apps/tests/msg/rpmsg-ping.c
Print the max size of the RX and TX buffer payloads. This allows to test the new API implemented in #521 in the CI.
> apps: Add use of rpmsg_virtio_get_tx/rx_buffer_size API

- lib/service/rpmsg/rpc/rpmsg_rpc_client.c
The if (&rpc->ept) comparison will always evaluate as 'true', since rpc == &rpc->ept and rpc is previously checked to be valid.
This produces an error when building open-amp with gcc >= 13.
> Fix https://github.com/OpenAMP/open-amp/issues/455

- lib/rpmsg/rpmsg_virtio.c
In rpmsg host side, the tx buffer index is not assigned when this buffer is obtained from the reclaimer list, this commit let rpmsg_virtio_get_tx_buffer() always gets correct idx.
Note: the idx in rpmsg host side is not used, so this commit is just an **improvement** and not fix any issue.
> rpmsg: let rpmsg_virtio_get_tx_buffer() always return idx in host side

- lib/include/openamp/rpmsg.h
- lib/rpmsg/rpmsg.c
- lib/rpmsg/rpmsg_internal.h
- lib/rpmsg/rpmsg_virtio.c
issue description:​
In our case, the` rpmsg_virtio_rx_callback()` is called in a rpmsg thread. Let's assume a situation, when `my_cb `has already got the ept in rpmsg thread,  user service thread just right called `my_deinit` to excute rpmsg_destroy_ept and released ept, at this time, the execution of ept ->cb has not been completed in rpmsg thread. so , there is a used after free about the ept.
Assuming we choose to fix this situation at the user level, we can continue to refer to the following examples:
```
void my_cb(...)
{
atomic_fetch_add(&g_priv->refcnt, 1); // 2*
....
if (atomic_fetch_sub(&g_priv->refcnt, 1) == 1) {
rpmsg_destroy_ept(&g_priv->ept);
free(g_priv);
}
}
void my_init(void)
{
g_priv = malloc(sizeof(*g_priv));
atomic_init(&g_priv->refcnt, 1);
g_priv->ept.cb = my_cb; …
```
> rpmsg: add release cb and refcnt in endpoint to fix ept used-after-free

- lib/remoteproc/remoteproc.c
remoteproc: clear bitmap in remoteproc_stop()
Fix parse res_table failed when repeat start the remoteproc.
If we don't clear the bitmap it will failed in
handle_vdev_rsc() -> remoteproc_allocate_id()
> remoteproc: clear bitmap when stop/shutdown

- lib/rpmsg/rpmsg_virtio.c
Add RPMSG_ASSERT() to rpmsg_virtio_return_buffer() to check the possible virtqueue buffer add error.
> rpmsg_virtio: add RPMSG_ASSERT to check the virtqueue add error

- lib/service/rpmsg/rpc/rpmsg_rpc_client.c
- lib/service/rpmsg/rpc/rpmsg_rpc_server.c
Hi,
The following PR fixes open-amp compilation with Vitis 2023.2 for cortex-R5F core. The compilation process stops with two errors in `rpmsg_rpc_server.c` and rpmsg_rpc_client.c due to undeclared `EINVAL`.
Let me know if you have any suggestions on this patch or better ideas on how to fix this issue(maybe in libmetal).
Please see the logs attached. 
```
/YOYO//workspace/ultra96_platform/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/include/xparameters.h:228: note: this is the location of the previous definition
| 
/YOYO//workspace/ultra96_platform/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/openamp/src/lib/service/rpmsg/rpc/rpmsg_rpc_server.c: In function 'rpmsg_endpoint_server_cb':
[ERROR] /YOYO//workspace/ultra96_platform/psu_cortexr5_0/freertos_psu_cortexr5_0/bsp/libsrc/openamp/src …
```
> Add missing include with EINVAL definition

- lib/remoteproc/remoteproc_virtio.c
Should init the device ID when create the virtio device.
> remoteproc_virtio: initialize the virtio device id when create vdev

- lib/rpmsg/rpmsg_internal.h
- lib/rpmsg/rpmsg_virtio.c
This commit fix one issue, before this commit, if `rpmsg_hold_rx_buffer()` is called in the endpoint callback to hold current received buffer and call` rpmsg_release_rx_buffer()` to release this buffer immediately.
This buffer will be returned to the virtqueue in `rpmsg_virtio_release_rx_buffer()` and returned to virtqueue again in `rpmsg_virtio_return_buffer()` after the `ept->cb()`.
So same buffer returned to the virtqueue twice, error happened.
Follow shows this process:
```
rpmsg_virtio_rx_callback()
- get rp_hdr
- ept->cb(data = RPMSG_LOCATE_DATA(rp_hdr))
- rpsmg_hold_rx_buffer(data)
- rpmsg_release_rx_buffer(data) here has returned buffer to virtqueue
- rpmsg_virtio_return_buffer() return same buffer to virtqueue again
```
The root cause of this issue is that the RPMSG_BUF_HELD has …
> openamp: change rx buffer hold flag to count

- lib/remoteproc/remoteproc_virtio.c
Only the first index of the vring_info is set to 0. Apply the memset to the whole memory allocated.
> remoteproc_virtio: fix vrings_info structure init

- lib/remoteproc/elf_loader.c
Unlike the Linux rproc elf loader, the OpenAMP elf loader loads the remote elf program segments to their load addresses instead of their link addresses. This results in memory corruption when the remote firmware attempts to relocate segments from their link addresses to load addresses at runtime such as the data section.
Signed-off-by: Umair Khan <umair_khan@mentor.com>
> Fixes #550: OpenAMP elf loader loads ELF sections to their load addresses

- apps/examples/load_fw/load_fw.c
The remoteproc_load_noblock() is a non-blocking API designed to load the remote firmware in streaming mode. The application has to continue supplying the firmware data blocks until the complete firmware is loaded. The load_fw example does this and checks the `nlen` variable (returned by the remoteproc_load_noblock() API) for zero to determine if the firmware loading is complete. However, `nlen` (contains the filesize of the next program header) alone can't be taken as the sufficient condition to mark the completion of firmware loading as 0 is a valid value for filesize for sections that don't require loading to the target memory such as the .bss section. This patch proposes checking filesize as well as memsize as a better metric to mark completion of the firmware loading loop.
> load_fw: The firmware loading loop terminates prematurely

- lib/include/openamp/rpmsg_virtio.h
- lib/remoteproc/remoteproc_virtio.c
- lib/rpmsg/rpmsg_virtio.c
remoteproc_virtio: optimize the remoteproc virtio transport layer
1. Implement the rproc_virtio_create_virtqueues() and rproc_virtio_delete_virtqueues()
2. Becase item 1, modified the `rpmsg_init_vdev_with_config()` also
> remoteproc_virtio: optimize the remoteproc virtio transport layer

- lib/remoteproc/elf_loader.c
The elf loader assumes that the last ELF program segment will always be a LOAD type segment. I deduce this from the fact that the elf_load() function, when loading the remote ELF sections during the RPROC_LOADER_READY_TO_LOAD stage, compares the last load segment num to the total ELF sections to determine if the loading is complete and it can move to the next stage RPROC_LOADER_POST_DATA_LOAD. If the last program segment in the ELF is not of type LOAD, the last loaded LOAD segment never equals total ELF sections. This creates an error condition and the firmware loading fails. This patch fixes this issue by comparing the last loaded LOAD segment number with the max LOAD segment number in the ELF.
This PR fixes OpenAMP#552
Signed-off-by: Muhammad Umair Khan <umair_khan@mentor.com>
> remoteproc: fix management of non loadable segments

- lib/include/openamp/remoteproc.h
- lib/include/openamp/remoteproc_virtio.h
- lib/include/openamp/rpmsg.h
- lib/include/openamp/rpmsg_virtio.h
- lib/include/openamp/virtio.h
- lib/remoteproc/remoteproc.c
- lib/remoteproc/remoteproc_virtio.c
- lib/rpmsg/rpmsg_virtio.c
openamp: move notify_wait() in rpmsg virtio to rpmsg, this ops can do in rpmsg without coupling to virtio.
> openamp: decouple rpmsg virtio and remoteproc

- lib/include/openamp/rpmsg_virtio.h
- lib/rpmsg/rpmsg_virtio.c
These functions are only used internally by rpmsg_virtio but are exposed in rpmsg_virtio.h which is included by users of the OpenAMP API. These functions reach into virtio structs which is a layering issue. They also have equivalents in the virtio API which should be used instead for this access. Remove these functions from the header before they get used by someone and turn into API.
> Remove layer breaking functions from rpmsg_virtio

- lib/remoteproc/remoteproc.c
* Since remoteproc_get_rsc_table() returns RPROC_ERR_PTR and never NULL, use RPROC_IS_ERR() to check the return value.
> remoteproc: Fix the NULL vs RPROC_IS_ERR() bug for remoteproc_get_rsc_table()

- apps/system/linux/machine/generic/platform_info.c
Do not directly call into io->close(), use the accessor function. While here, do not free the io structure as we did not allocate it and have no way to know how it was allocated.
> apps: system: linux: Use metal_io_finish() for closing io

- apps/examples/load_fw/zynqmp_apu_lcm_rproc_example.c
- apps/examples/load_fw/zynqmp_r5_lcm_rproc_example.c
- apps/examples/load_fw/zynqmp_rpu_lcm_rproc_example.c
- apps/system/linux/machine/generic/platform_info.c
The remoteproc_mem struct contents are internal to remoteproc. The struct should be accessed using the provided accessors, not directly. This is done in preperation of making this struct opaque to code outside of the remoteproc drivers.
> apps: linux: generic: Use accessor functions for struct remoteproc_mem

- apps/examples/echo/rpmsg-echo.c
- apps/examples/echo/rpmsg-ping.c
- apps/examples/nocopy_echo/rpmsg-nocopy-ping.c
- apps/tests/msg/rpmsg-flood-ping.c
- apps/tests/msg/rpmsg-nocopy-ping.c
- apps/tests/msg/rpmsg-ping.c
- lib/include/openamp/rpmsg.h
- lib/rpmsg/rpmsg.c
- lib/rpmsg/rpmsg_virtio.c
In patch 3 of this series you can see core of the issue, applications have no way of finding if the transport layer under RPMsg has a maximum supported message size. The examples end up having to look directly into the transport layer to find this info. With this API they can ask the RPMsg layer without having to know about the backing transport layer. This is better API layering and allows the core of the examples to work across any transport layer.
> Add RPMsg API to get buffer size

- lib/virtio/virtqueue.c
Length was being read without first invalidating. There are functions that handle invalidating and reading from vq_ring members. Use those here.
> virtio: Use virtqueue_get_buffer() helpers

- lib/include/openamp/remoteproc.h
- lib/remoteproc/remoteproc.c
Having these functions as inline header functions forces the contents of struct remoteproc_mem to remain externally exposed. It also does not save space in most cases as every call-site gets the full contents of the function instead of just a call instruction. Make these normal functions like all others in remoteproc.h.
> remoteproc: Un-inline remoteproc_init_mem() and remoteproc_add_mem()

- apps/examples/linux_rpc_demo/linux_rpc_demod.c
The contents of this struct are internal to the RPMsg layer. Access should only happen using accessor functions.
> apps: linux_rpc_demo: Do not access members of rpmsg_endpoint

- lib/include/openamp/virtqueue.h
- lib/virtio_mmio/virtio_mmio_drv.c
This should hold a pointer to an metal_io_region, make that the type.
Also fix the comment, this region holds the address of the message buffers, not the vring's descriptor table nor available/used rings. It is only used for virt-to-phys/phys-to-vert on the buffers pointed to by these descriptors.
This comment seems to have cause an issue in virtio_mmio_drv where this region was used to translate the address of the vring descriptors. This may have worked if the vring descriptors where part of the same IO space as the buffers they point to, but this is not guaranteed to always be the case. Fix that here.
> virtqueue: Fix comment on shm_io and fix type

- cmake/options.cmake
- lib/include/openamp/rpmsg_virtio.h
- lib/include/openamp/virtio.h
The use of the master and slave wors in configs and API are now deprecated since 2 years, we can remove the associated code.
> lib: remove deprecated MASTER/SLAVE configuration

- lib/include/openamp/rpmsg_rpc_client_server.h
- lib/service/rpmsg/rpc/rpmsg_rpc_client.c
Fix following warning by updating bad rpc_id parameter type in the rpmsg_rpc_client_send() API.
Align the rpc_id type to the one used in rpmsg_rpc_server_send().
/github/workspace/lib/service/rpmsg/rpc/rpmsg_rpc_client.c:60:9: error: ‘memcpy’ reading 8 bytes from a region of size 4 [-Werror=stringop-overread]
1286
60 |  memcpy(tmpbuf, &rpc_id, MAX_FUNC_ID_LEN);
1287
|  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1288
/github/workspace/lib/service/rpmsg/rpc/rpmsg_rpc_client.c:51:40: note: source object ‘rpc_id’ of size 4
1289
51 |  unsigned int rpc_id, void *request_param,
1290
|  ~~~~~~~~~~~~~^~~~~~
> lib: rpmsg_rpc: fix compilation warning and bad API

- .github/actions/build_ci/Dockerfile
- .github/actions/build_ci/README.md
- .github/actions/build_ci/entrypoint.sh
The "open-amp lib Continuous Integration / check builds on different platforms" check has failed due to a Docker environment update.
Issues were found related to timezone settings and pip3. Upon fixing these, a build error was reported by GCC (likely a new version) in rpmsg_rpc_client.c.
This PR addresses both issues to restore a working CI environment.
> Fix broken CI 

- apps/machine/zynq7/platform_info_remoteproc_master.c
- apps/tests/msg/rpmsg-nocopy-echo.c
Some potentially offensive terms are still present in the code, Replace them.
> apps: remove remaining master terminology

- lib/virtio/virtio.c
The comments states this was kept for "future use", that was a decade ago.. Remove this never used function and associated data.
> virtio: Remove never used virtio_feature_name()

- lib/include/openamp/remoteproc.h
- lib/include/openamp/rpmsg.h
- lib/include/openamp/rpmsg_rpc_client_server.h
- lib/include/openamp/virtio.h
- lib/include/openamp/virtio_mmio.h
- lib/rpmsg/rpmsg_internal.h
- lib/rpmsg/rpmsg_virtio.c
Fix warnings reported by Doxygen on the open-amp lib
> fix Doxygen warnings

- lib/include/openamp/virtio.h
As part of the deprecation process for VIRTIO_DEVICE_ONLY and VIRTIO_DRIVER_ONLY, we should still support builds without errors when possible.
For legacy support, define VIRTIO_DRIVER_SUPPORT and VIRTIO_DEVICE_SUPPORT default values based on VIRTIO_DEVICE_ONLY and VIRTIO_DRIVER_ONLY.
> [FIX FOR V2024.05] lib: fix build error using legacy VIRTIO_DEVICE/DRIVER_ONLY

- lib/include/openamp/virtio_mmio.h
- lib/virtio_mmio/virtio_mmio_drv.c
A virtual metal_device is created, then the needed IO regions are created and added to this device. Immediately we extract these same regions back out and make use of them. There is no reason to do this, instead simply use the created IO regions.
This also removes the need to have struct metal_device defined to have more than one IO region (METAL_MAX_DEVICE_REGIONS), which is not the default and can change per-platform. If the libmetal library was built with the default value for METAL_MAX_DEVICE_REGIONS, then this would have led to runtime failures.
> virtio_mmio: Remove unneeded use of libmetal device

- lib/remoteproc/remoteproc.c
* When rproc->ops fails, the state of rproc should not be updated.
Fix #599
> remoteproc: Do not update the rproc state if rproc->ops fails

- lib/rpmsg/rpmsg_virtio.c
> rpmsg: Replace rvdev->vdev with vdev in rpmsg_init_vdev_with_config

- lib/include/openamp/virtio.h
- lib/remoteproc/remoteproc_virtio.c
add helpful judge for final_features is NULL and update vdev->features in virtio_negotiate_features
> openamp/virtio.h: update vdev->features and make final_features optional

- README.md
- cmake/options.cmake
- lib/rpmsg/rpmsg_virtio.c
Add VQ_RX_EMPTY_NOTIFY config to define the behavior. If VQ_RX_EMPTY_NOTIFY is disabled, notify the other side each time a buffer is released. If VQ_RX_EMPTY_NOTIFY is enabled, only send one notification when the RX queue is empty to improve performance.
> rpmsg: Allow to send virtqueue_kick only when RX queue is empty

- .github/actions/build_ci/entrypoint.sh
- .github/workflows/continuous-integration.yml
- .github/workflows/heathcheck.yml
This PR brings open-amp up to parity with libmetal with regard to Zephyr CI testing
open-amp did not have the latest SDK discovery code nor the sdk install reduction of verbosity that were already in libmetal so this PR is a bit bigger than the one for libmetal but the end result is the same.
> CI: Zephyr, test against known working version and also the very latest on main

- lib/remoteproc/remoteproc_virtio.c
- lib/rpmsg/rpmsg_virtio.c
The CPU yield is not supported by all OSes/processors. If not supported, this causes a busy loop that monopolizes the CPU. Replace it with the new metal_yield, it would be managed at the OS level and dispatched to metal_cpu_yield, metal_sleep_usec, or others.
> rpmsg_virtio.c: replace metal_cpu_yield to metal_yield

- lib/rpmsg/rpmsg_virtio.c
If rpmsg_virtio_notify_wait() returns RPMSG_SUCCESS, we should not directly return NULL, but call rpmsg_virtio_get_tx_buffer to get the tx buffer again.
This is the new PR of https://github.com/OpenAMP/open-amp/pull/614, and you can find the detail discussions in https://github.com/OpenAMP/open-amp/pull/614
> rpmsg_virtio: fix rpmsg_virtio_get_tx_payload_buffer() error

- cmake/options.cmake
The applications are now in the openamp-system-reference repository. The "apps" folder is now deprecated and should be removed in coming releases.
> options: make WITH_APPS cmake option deprecated

- lib/include/openamp/remoteproc.h
- lib/include/openamp/rpmsg.h
- lib/remoteproc/remoteproc.c
- lib/rpmsg/rpmsg.c
Fix issue #625 reported by @jonny-svaerd-arm 
Fix `safe_strcpy()`  argument that provides the size of the source string. Indeed, if the source string is of type char*, it is not valid to use `sizeof` to determine its length. Use `strnlen` to get the size of the string while ensuring that we have a maximum size.
On the contrary, it is preferable to use sizeof on `ept->name`, that is an array of char
> Fix safe_strcpy calls

- lib/include/openamp/virtio.h
Buffer management is different for different transport layer:
For MMIO transport layer, the buffer can direclty malloced from
the gust os heap beacase the hypervisor can access all the memmory own
by guest os.
For remoteproc transpor layer, the buffer should be malloced from
the share memory region to make sure the remote core can access this
buffer too.
So add memory ops in virtio device to make different transport/device can
implement their own share memory management.
> virtio.h: add memory operation for virtio device

- .github/actions/build_ci/entrypoint.sh
The name of the board has been updated since the Zephyr commit:
d8cfa6fb2916 ("boards: nxp: convert lpcxpresso54114 to hwmv2")
Fix the build command according to the new name.
The update is compatible with the Zephyr v3.7.
> CI: fix zephyr test on Zephyr for lpcxpresso54114 board

- lib/include/openamp/virtio.h
Add parentheses around the "vdev" parameter to avoid side effects.
This fixes a build error when using the macro in the following way:
if (VIRTIO_ROLE_IS_DEVICE(&my_context->vdev))
The error encountered:
openamp/open-amp/lib/include/openamp/virtio.h:89:49: error: invalid type argument of ‘->’ (have ‘struct virtio_device’)
89 |  (VIRTIO_ENABLED(VIRTIO_DRIVER_SUPPORT) && (vdev->role) == VIRTIO_DEV_DRIVER)
> lib: virtio: Fix VIRTIO ROLE_XXXX macro definitions

- lib/include/openamp/virtio.h
-    virtio.h: add new api virtio_has_feature()
```c
virtio_has_feature() can be easily used to heck if the virtio device
support a specific feature.
And assgin feature to vdev->feature for virtio device role when get
features, so the virtio device side can use virtio_has_featrue() to
check weather the virtio device support a feature.
```
-    virtio.h: add new feature bit VIRTIO_F_ANY_LAYOUT
```c
Follow the virtio spec, this feature bit indicates that the device
accepts arbitrary descriptor layouts.
```
> virtio.h: add some user-friendly apis

- CMakeLists.txt
We currently support an old version of CMake (3.0.2) that was released in 2018.
This requires adding specific policies to support the evolution to the latest versions of Zephyr.
Update the minimum version to 3.16, aligned with the libmetal.
By updating to CMake 3.16 as the minimum version, we can also clean up the following policy add-ons:
- CMP0048 added in CMake v3.0
- CMP0077 added in CMake v3.13
Associated PR in libmetal library: https://github.com/OpenAMP/libmetal/pull/327
> cmake: update cmake minimum support to 3.16

- .github/actions/build_ci/entrypoint.sh
These are the current versions and have already been tested via the Zephyr health check job.
> CI: update known working version of Zephyr and its SDK

- lib/rpmsg/rpmsg_virtio.c
If rvdev is deinited, using rvdev->vdev may cause a use-after-free error.
> rpmsg_virtio: deinit rvdev->vdev when rvdev is deinited
