OpenAMP/open-amp

- apps/tests/master/baremetal/func_test_suite/test_suite.h
- apps/tests/master/linux/kernelspace/rpmsg_func_test_kern_app/rpmsg_func_test_kern_app.c
- apps/tests/remote/baremetal/func_test_suite/test_suite.h
- common/compiler/compiler.h
- remoteproc/remoteproc.h
- rpmsg/rpmsg.h
- rpmsg/rpmsg_core.h
see https://github.com/OpenAMP/open-amp/pull/9
> Introduce packet struct macros for supported compilers

- lib/common/firmware.c
- lib/common/hil.c
- lib/include/openamp/env.h
- lib/include/openamp/machine/machine_common.h
- lib/include/openamp/system/generic/machine/zynq7/machine_system.h
- lib/proxy/rpmsg_retarget.c
- lib/remoteproc/drivers/zynq_a9_trampoline.S
- lib/remoteproc/drivers/zynq_remoteproc_a9.c
- lib/remoteproc/drivers/zynqmp_remoteproc_a53.c
- lib/remoteproc/elf_loader.c
- lib/remoteproc/remoteproc.c
- lib/remoteproc/rsc_table_parser.c
- lib/rpmsg/remote_device.c
- lib/rpmsg/rpmsg.c
- lib/rpmsg/rpmsg_core.c
- lib/system/generic/CMakeLists.txt
- lib/system/generic/bm_env.c
- lib/system/generic/env.c
- lib/system/generic/machine/zynq7/machine_system.c
- lib/system/generic/machine/zynqmp_r5/CMakeLists.txt
- lib/system/generic/machine/zynqmp_r5/machine_system.c
- lib/virtio/virtio.c
- lib/virtio/virtqueue.c
-Fix bug happening on deinit where memory deallocation is not done correctly.
-Fix bug replace logical-AND by bit-AND with ipi_chn_mask  …
-Invalidate cache instead of disabling on exit
-Get drivers file to use platform_isr instead of hil_isr
-Fix some compilation warnings, clean comments, file renaming, make some local variable static
> Esw sync 1

- cmake/platforms/zynq7_generic.cmake
- cmake/platforms/zynqmp_r5_generic.cmake
Optimization setting shall be set by cmake based on debug/release.
This relates to libmetal commit 1d6d72d.
> cmake options: change optimization settings

- apps/echo_test/echo_testd.c
- apps/system/linux/machine/generic/platform_info.c
- apps/system/linux/machine/generic/rsc_table.c
- apps/system/linux/machine/generic/rsc_table.h
- lib/common/hil.c
- lib/include/openamp/rpmsg_core.h
- lib/remoteproc/drivers/linux_remoteproc.c
- lib/rpmsg/remote_device.c
- lib/rpmsg/rpmsg.c
- lib/rpmsg/rpmsg_core.c
This patch series fixes using OpenAMP RPMsg between two Linux processes.
It is tested with echo test and matrix multiplication.
> Linux userspace

- lib/include/openamp/rpmsg.h
- lib/rpmsg/rpmsg.c
- lib/rpmsg/rpmsg_core.c
> Master decouple staging

- lib/include/openamp/open_amp.h
> open_amp.h: fix struct element so it builds

- .travis.yml
> ci: Add simple build test with Zephyr for open-amp

- lib/include/openamp/virtqueue.h
- lib/virtio/virtqueue.c
Signed-off-by: Wendy Liang <jliang@xilinx.com>
> virtqueue: name is const in virtqueue_create()

- apps/examples/rpc_demo/CMakeLists.txt
- apps/examples/rpc_demo/rpc_demo.c
- apps/examples/rpc_demo/rpc_demod.c
- apps/examples/rpc_demo/rpmsg-rpc-demo.h
- lib/include/openamp/rpmsg_retarget.h
- lib/proxy/rpmsg_retarget.c
Renable RPMsg RPC demo with the latest RPMsg changes
> Renable RPMsg RPC Demo

- lib/include/openamp/rpmsg.h
- lib/rpmsg/rpmsg_virtio.c
Few fixes for compilation issue with IAR
> Master decouple staging: minor fixes

- apps/examples/echo/rpmsg-ping.c
- apps/examples/matrix_multiply/matrix_multiply.c
- apps/examples/rpmsg_sample_echo/rpmsg-sample-ping.c
- apps/tests/msg/rpmsg-ping.c
- lib/rpmsg/rpmsg_virtio.c
* A typo in a comment
* rename src -> dest in ns_bind_callback
> A few minor fixes

- lib/rpmsg/rpmsg_virtio.c
don't return wrong buffer size error if get buffer size is 0
> Rpmsg virtio fix nobuffer

- apps/tests/msg/CMakeLists.txt
- apps/tests/msg/rpmsg-flood-ping.c
- apps/tests/msg/rpmsg-update.c
Add RPMsg flood ping to test sending RPMsg continuously until there is no available buffers.
> Rpmsg flood ping

- apps/machine/zynq7/rsc_table.c
- apps/machine/zynq7/rsc_table.h
- apps/machine/zynqmp_r5/platform_info.c
- apps/machine/zynqmp_r5/rsc_table.c
- apps/machine/zynqmp_r5/rsc_table.h
- lib/include/openamp/remoteproc.h
- lib/remoteproc/rsc_table_parser.c
Remove resource types which are not supported by Linux kernel
> Remove resource types which doesn't have kernel support

- lib/include/openamp/remoteproc_virtio.h
- lib/include/openamp/virtio.h
- lib/remoteproc/remoteproc.c
- lib/remoteproc/remoteproc_virtio.c
@galak, @wjliang and @arnop2, this patch series fix the bug found inremoteproc_virtio.c
> Fix in remoteproc_virtio

- lib/remoteproc/elf_loader.c
> fix elf loader off-by-one bug

- apps/tests/msg/rpmsg-flood-ping.c
If the memory is not normal memory, memcmp will not work.
Compare the received buffers byte by byte.
Signed-off-by: Wendy Liang <wendy.liang@xilinx.com>
> tests: flood ping: compare input byte by byte

- apps/machine/zynq7/zynq_a9_rproc.c
- apps/machine/zynqmp/zynqmp_linux_r5_proc.c
- apps/machine/zynqmp_r5/zynqmp_r5_a53_rproc.c
- apps/system/generic/machine/zynq7/helper.c
- apps/system/generic/machine/zynqmp_r5/helper.c
- apps/system/linux/machine/generic/platform_info.c
This pull request is based on the libemtal IRQ API update pull request https://github.com/OpenAMP/libmetal/pull/72
> Master irq update for Xilinx platform

- docs/img-src/gen-graph.py
> docs: gen-graph: Fix broken typo'd sys.exit()

- docs/img-src/gen-graph.py
> scripts: gen-graph: Remove unused Digraph import

- lib/remoteproc/remoteproc.c
Signed-off-by: ligd <liguiding@pinecone.net>
> openamp: fix remoteproc_load hasn't update rsc_io

- apps/CMakeLists.txt
- apps/examples/load_fw/CMakeLists.txt
- apps/examples/load_fw/common.h
- apps/examples/load_fw/load_fw.c
- apps/examples/load_fw/mem_image_store.c
- apps/examples/load_fw/platform_info.c
- apps/examples/load_fw/platform_info.h
- apps/examples/load_fw/zynqmp_apu_lcm_rproc_example.c
- apps/examples/load_fw/zynqmp_rpu_lcm_rproc_example.c
- apps/machine/zynqmp/CMakeLists.txt
- apps/machine/zynqmp/platform_info.c
- apps/machine/zynqmp_r5/platform_info.c
- apps/machine/zynqmp_r5/platform_info.h
- apps/system/generic/machine/zynqmp_r5/CMakeLists.txt
- apps/system/linux/machine/generic/platform_info.c
- cmake/options.cmake
Update the load_fw demo for Xilinx to use new power management APIs.
Update other demos to incorporate new Xilinx BSP.
Most of this code is specific to the Xilinx hardware, but there are a few fixes to generic code.
Signed-off-by: Ed Mooring <ed.mooring@linaro.org>
> Xilinx: Update examples

- lib/include/openamp/rpmsg_virtio.h
- lib/remoteproc/remoteproc_virtio.c
so the rpmsg could access the configuration space as needed
> implement rproc_virtio_read_config/rproc_virtio_write_config

- apps/machine/zynqmp/zynqmp_linux_r5_proc.c
According to coding rules replace spaces by tabs.
> apps: zynqmp:fix indentation

- .github/workflows/continuous-integration.yml
- scripts/ci/check_compliance.py
The webispy/checkpatch-action does not seem to work properly.
Even if it detects coding style issue, the return status is successful.
This patch replaces the action by the compliance python script obtained
from the Zephyr project.
This script also runs gitlint to check commit messages.
> CI: rework compliance test

- CMakeLists.txt
Signed-off-by: Ed Mooring <ed.mooring@xilinx.com>
> CMake: Update minimum CMake version to 3.0.2.

- apps/machine/zynqmp/platform_info.c
- apps/machine/zynqmp/platform_info.h
- apps/machine/zynqmp/zynqmp_linux_r5_proc.c
- apps/machine/zynqmp_r5/platform_info.c
- apps/machine/zynqmp_r5/platform_info.h
- apps/machine/zynqmp_r5/zynqmp_r5_a53_rproc.c
As result of NO IPI demo commits, there are compilation issues.
Update to remedy this for R5 demos
> apps: demos without IPI

- apps/examples/echo/rpmsg-echo.c
- apps/examples/echo/rpmsg-ping.c
- apps/examples/matrix_multiply/matrix_multiply.c
- apps/examples/matrix_multiply/matrix_multiplyd.c
- apps/examples/rpc_demo/rpc_demo.c
- apps/examples/rpc_demo/rpc_demod.c
- apps/examples/rpmsg_sample_echo/rpmsg-sample-echo.c
- apps/examples/rpmsg_sample_echo/rpmsg-sample-ping.c
- apps/machine/microblaze_generic/platform_info.c
- apps/machine/microblaze_generic/platform_info.h
- apps/machine/zynq7/platform_info.c
- apps/machine/zynq7/platform_info.h
- apps/machine/zynqmp/platform_info.c
- apps/machine/zynqmp/platform_info.h
- apps/machine/zynqmp_r5/platform_info.c
- apps/machine/zynqmp_r5/platform_info.h
- apps/system/linux/machine/generic/platform_info.c
- apps/system/linux/machine/generic/platform_info.h
- apps/tests/msg/rpmsg-flood-ping.c
- apps/tests/msg/rpmsg-ping.c
- apps/tests/msg/rpmsg-update.c
as per https://github.com/OpenAMP/open-amp/issues/231 
update platform_release_rpmsg_vdev  to cleanup openamp environment
> Upstream issue 231

- apps/examples/echo/rpmsg-echo.c
- apps/examples/echo/rpmsg-echo.h
- apps/examples/echo/rpmsg-ping.c
- apps/examples/matrix_multiply/matrix_multiply.c
- apps/examples/matrix_multiply/matrix_multiply.h
- apps/examples/matrix_multiply/matrix_multiplyd.c
- apps/examples/rpc_demo/rpc_demo.c
- apps/examples/rpc_demo/rpc_demod.c
- apps/examples/rpc_demo/rpmsg-rpc-demo.h
- apps/examples/rpmsg_sample_echo/rpmsg-sample-echo.c
- apps/examples/rpmsg_sample_echo/rpmsg-sample-ping.c
- apps/machine/zynq7/platform_info.h
- apps/machine/zynqmp_r5/platform_info.h
- apps/tests/msg/rpmsg-flood-ping.c
- apps/tests/msg/rpmsg-ping.c
- apps/tests/msg/rpmsg-ping.h
- apps/tests/msg/rpmsg-update.c
- lib/include/openamp/rpmsg_retarget.h
- lib/proxy/rpmsg_retarget.c
Add license information when missing
Add also copyrights when possible to determine origin.
> Add missing licence information

- lib/rpmsg/rpmsg_internal.h
openamp: replace while(1) to metal_assert in RPMSG_ASSERT
> openamp: replace while(1) to metal_assert in RPMSG_ASSERT

- MAINTAINERS.md
Update Ed Mooring's email address and remove the machine specific
entries.
Signed-off-by: Ed Mooring <ed.mooring@gmail.com>
> MAINTAINERS: Update maintainer email address.

- lib/include/openamp/rpmsg.h
since it is deprecated for while
> rpmsg: remove rpmsg_init_ept

- docs/data-structure.md
Realign data structure description with the code.
The Description of the libmetal API is removed.
> doc: clean-up data structures

- README.md
Fixe some links that are outdated or broken in the readme.md
> README fix some links

- lib/CMakeLists.txt
- lib/include/openamp/virtio.h
- lib/include/openamp/virtio_mmio.h
- lib/include/openamp/virtqueue.h
- lib/virtio/virtio.c
- lib/virtio/virtqueue.c
- lib/virtio_mmio/CMakeLists.txt
- lib/virtio_mmio/virtio_mmio.c
- zephyr/CMakeLists.txt
- zephyr/README
- zephyr/module.yml
virtio-mmio framework for lib open-amp
> Virtio exp

- lib/virtio/virtqueue.c
openamp: add available_idx to dump
> openamp: add available_idx to dump

- lib/remoteproc/rsc_table_parser.c
Updated handle_vdev_rsc to return error if a unique id cannot be assigned
> handle_vdev_rsc must return error if notifyid cannot be assigned

- lib/include/openamp/virtio.h
- lib/include/openamp/virtio_ring.h
- lib/include/openamp/virtqueue.h
Complete virtio structure doxygen description initiate in https://github.com/OpenAMP/open-amp/pull/507
> Doxygen update for virtio structures

- .github/workflows/stales.yml
Add action to add stale label on issues and PR when no activity during 45 days.
> github action: add stales action

- cmake/options.cmake
- lib/include/openamp/virtio_mmio.h
- lib/include/openamp/virtio_mmio_hvl.h
- lib/virtio/virtqueue.c
- lib/virtio_mmio/CMakeLists.txt
- lib/virtio_mmio/virtio_mmio_drv.c
- lib/virtio_mmio/virtio_mmio_hvl.c
- lib/virtio_mmio/virtio_serial_drv.c
Added support for hypervisor-less virtio.
- HVP dispatch function table
- Semaphore-based configuration synchronization mechanism when in yield-capable context
> virtio-mmio: hypervisor-less mode
